name: UI To DockerHub

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Node.js 18.16.1
        uses: actions/setup-node@master
        with:
          node-version: "18.16.1"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: "8.6.3"

      - name: Build
        run: pnpm install && pnpm build:prod

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_DOCKERHUB_USERNAME }}
          password: ${{ secrets.ALIYUN_DOCKERHUB_PWD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./
          push: true
          tags: |
            registry.cn-hangzhou.aliyuncs.com/jiangyitao/yqhp-web-ui:latest
            registry.cn-hangzhou.aliyuncs.com/jiangyitao/yqhp-web-ui:1.0.9
